## Methods

### Study Species & Locale

*Araptus attenuatus* Wood (Curculionidae) is a bark beetle endemic to the Sonoran desert and known only to inhabit the senescing stems of the Euphorb *Euphorbia lomelii* (Garrick *et al.* 2013).  Both plant and insect are co-distributed throughout the Sonoran desert in Baja California, Mexico with at least two relictual populations in the mainland states of Sonora and Sinaloa.  The distribution of spatial genetic structure in both host plant and insect reveal marked phylogeographic structuring (Garrick *et al.* 2009, 2013) with clear evidence of post-Pleistocene range expansion, multiple glacial refugia, and clear spatial partitioning on the existing desert landscape.  Throughout its range, the genetic structure of *A. attenuatus* suggests cryptic speciation with mtDNA sequence divergence of 8-12 % separating clades—one on mainland Mexico and two sharing a zone of sympatry in the southern region of the Baja California peninsula.  

For this project, individuals were sampled from locales known to be of only the largest and main mtDNA clade from peninsular Baja California.  Previous work in this species has revealed a clade-specific diagnostic SNP marker, which all individuals were screened to ensure observed genetic and epigeneic differences were monophyletic.




### Methylation-Sensitive AFLP 



```{r}
adapters <- data.frame( Target = c("Adaptors",
                                   "EcoRI-F",
                                   "EcoRI-R",
                                   "HPAII/MspI-F",
                                   "HPAII/MspI-R",
                                   "Preselective Primers",
                                   "EcoRI + A",
                                   "HPAII/MspI + C",
                                   "Selective Primers",
                                   "EcoRI + ACT",
                                   "HPAII/MspI + CGT"))
adapters$Sequences <- c("",
                        "5’-CTCGTAGACTGCGTACC",
                        "5’-AATTGGTACGCAGTCTAC",
                        "5’-GACGATGAGTCCTGAG",
                        "5’-CGCTCAGGACTCAT",
                        "",
                        "5’-GACTGCGTACCAATTCA",
                        "5’-GACGATGAGTCCTGAGCGGC",
                        "",
                        "5’-GACTGCGTACCAATTCACT",
                        "5’-GACGATGAGTCCTGAGCGGCGT")
knitr::kable(adapters,caption="Table X: Adapters and primers sets used for msAFLP band selection.")
```


### Analyses




  
